version: "3.9"
services:
  app:
    depends_on:
      - db
    build: .
    restart: always
    ports:
      - "80:80"
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: infocenter
      MYSQL_USER: db_user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_HOST: '%'
    volumes:
      - "./mysql/db.sql:/docker-entrypoint-initdb.d/1.sql"
