FROM php:7.4-apache

RUN docker-php-ext-install mysqli && docker-php-ext-enable mysqli

COPY infocenter /var/www/html/infocenter
RUN sed -i 's/http:\/\/localhost/https:\/\/www.parduslogger.com/g' /var/www/html/infocenter/pardus_infocenter_share.user.js

# copy apache config
COPY apache/000-default.conf /etc/apache2/sites-enabled/000-default.conf

# enable SSL
RUN a2enmod ssl

EXPOSE 443